In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
p = [1096.95, 596.95, 896.95]

In [3]:
c = 30.1

In [4]:
prices = np.array(p)

In [5]:
prices

array([ 1096.95,   596.95,   896.95])

In [6]:
print(prices)

[ 1096.95   596.95   896.95]


In [7]:
prices * c

array([ 33018.195,  17968.195,  26998.195])