In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.random.randn(100)

In [3]:
A

array([  1.19993564e+00,  -1.07382909e-01,  -4.48656570e-01,
        -2.88730647e-01,  -6.87947112e-01,  -1.55323690e-01,
         6.21585294e-01,   6.03458264e-01,  -1.74007992e+00,
        -6.87242527e-01,   3.71267973e-01,  -7.75451209e-01,
        -9.82962702e-02,  -1.30264410e+00,   1.06524021e+00,
        -1.01460282e+00,  -3.72156601e-01,   4.65383336e-01,
         1.38725624e-01,   2.24821411e-01,  -8.46471670e-01,
        -1.35138896e+00,  -2.17394916e+00,  -4.34245305e-01,
         1.56569442e+00,   5.27921026e-02,   1.21255142e+00,
         6.89946529e-01,   1.44395598e+00,   1.24779707e+00,
         1.04922259e+00,   3.83530293e-01,  -1.10753424e+00,
         6.65443419e-01,  -7.01208396e-01,  -3.38254042e-01,
         1.47194135e+00,   8.88272184e-01,   8.90112746e-01,
         1.64150838e+00,  -1.43190934e+00,   8.40109551e-01,
        -9.16680829e-01,  -4.53802137e-01,   4.94865407e-01,
         6.70913480e-01,   1.72538013e-01,  -1.43523153e-01,
         2.85753159e-01,

In [4]:
A = 10*A + 50

In [5]:
A

array([ 61.99935645,  48.92617091,  45.5134343 ,  47.11269353,
        43.12052888,  48.4467631 ,  56.21585294,  56.03458264,
        32.59920076,  43.12757473,  53.71267973,  42.24548791,
        49.0170373 ,  36.97355901,  60.6524021 ,  39.8539718 ,
        46.27843399,  54.65383336,  51.38725624,  52.24821411,
        41.5352833 ,  36.48611042,  28.2605084 ,  45.65754695,
        65.65694425,  50.52792103,  62.12551419,  56.89946529,
        64.43955984,  62.4779707 ,  60.49222586,  53.83530293,
        38.92465764,  56.65443419,  42.98791604,  46.61745958,
        64.71941352,  58.88272184,  58.90112746,  66.41508382,
        35.68090663,  58.40109551,  40.83319171,  45.46197863,
        54.94865407,  56.7091348 ,  51.72538013,  48.56476847,
        52.85753159,  42.71932461,  45.92946367,  41.20408325,
        36.51300657,  50.272956  ,  53.43784363,  31.64754625,
        49.98820875,  43.90501655,  63.11614744,  37.03757198,
        44.39654678,  45.76149362,  38.5202606 ,  45.27

In [6]:
A.shape

(100,)

In [7]:
A.shape = (5, 20)

In [8]:
A

array([[ 61.99935645,  48.92617091,  45.5134343 ,  47.11269353,
         43.12052888,  48.4467631 ,  56.21585294,  56.03458264,
         32.59920076,  43.12757473,  53.71267973,  42.24548791,
         49.0170373 ,  36.97355901,  60.6524021 ,  39.8539718 ,
         46.27843399,  54.65383336,  51.38725624,  52.24821411],
       [ 41.5352833 ,  36.48611042,  28.2605084 ,  45.65754695,
         65.65694425,  50.52792103,  62.12551419,  56.89946529,
         64.43955984,  62.4779707 ,  60.49222586,  53.83530293,
         38.92465764,  56.65443419,  42.98791604,  46.61745958,
         64.71941352,  58.88272184,  58.90112746,  66.41508382],
       [ 35.68090663,  58.40109551,  40.83319171,  45.46197863,
         54.94865407,  56.7091348 ,  51.72538013,  48.56476847,
         52.85753159,  42.71932461,  45.92946367,  41.20408325,
         36.51300657,  50.272956  ,  53.43784363,  31.64754625,
         49.98820875,  43.90501655,  63.11614744,  37.03757198],
       [ 44.39654678,  45.76149362,  

In [9]:
A.reshape(100,1)

array([[ 61.99935645],
       [ 48.92617091],
       [ 45.5134343 ],
       [ 47.11269353],
       [ 43.12052888],
       [ 48.4467631 ],
       [ 56.21585294],
       [ 56.03458264],
       [ 32.59920076],
       [ 43.12757473],
       [ 53.71267973],
       [ 42.24548791],
       [ 49.0170373 ],
       [ 36.97355901],
       [ 60.6524021 ],
       [ 39.8539718 ],
       [ 46.27843399],
       [ 54.65383336],
       [ 51.38725624],
       [ 52.24821411],
       [ 41.5352833 ],
       [ 36.48611042],
       [ 28.2605084 ],
       [ 45.65754695],
       [ 65.65694425],
       [ 50.52792103],
       [ 62.12551419],
       [ 56.89946529],
       [ 64.43955984],
       [ 62.4779707 ],
       [ 60.49222586],
       [ 53.83530293],
       [ 38.92465764],
       [ 56.65443419],
       [ 42.98791604],
       [ 46.61745958],
       [ 64.71941352],
       [ 58.88272184],
       [ 58.90112746],
       [ 66.41508382],
       [ 35.68090663],
       [ 58.40109551],
       [ 40.83319171],
       [ 45

In [11]:
A = A.reshape(100,1)

In [12]:
A

array([[ 61.99935645],
       [ 48.92617091],
       [ 45.5134343 ],
       [ 47.11269353],
       [ 43.12052888],
       [ 48.4467631 ],
       [ 56.21585294],
       [ 56.03458264],
       [ 32.59920076],
       [ 43.12757473],
       [ 53.71267973],
       [ 42.24548791],
       [ 49.0170373 ],
       [ 36.97355901],
       [ 60.6524021 ],
       [ 39.8539718 ],
       [ 46.27843399],
       [ 54.65383336],
       [ 51.38725624],
       [ 52.24821411],
       [ 41.5352833 ],
       [ 36.48611042],
       [ 28.2605084 ],
       [ 45.65754695],
       [ 65.65694425],
       [ 50.52792103],
       [ 62.12551419],
       [ 56.89946529],
       [ 64.43955984],
       [ 62.4779707 ],
       [ 60.49222586],
       [ 53.83530293],
       [ 38.92465764],
       [ 56.65443419],
       [ 42.98791604],
       [ 46.61745958],
       [ 64.71941352],
       [ 58.88272184],
       [ 58.90112746],
       [ 66.41508382],
       [ 35.68090663],
       [ 58.40109551],
       [ 40.83319171],
       [ 45