In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
xy = [[x, y] for x in range(10) for y in range(5)]

In [4]:
xy = np.array(xy)

In [5]:
xy

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4],
       [4, 0],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4],
       [5, 0],
       [5, 1],
       [5, 2],
       [5, 3],
       [5, 4],
       [6, 0],
       [6, 1],
       [6, 2],
       [6, 3],
       [6, 4],
       [7, 0],
       [7, 1],
       [7, 2],
       [7, 3],
       [7, 4],
       [8, 0],
       [8, 1],
       [8, 2],
       [8, 3],
       [8, 4],
       [9, 0],
       [9, 1],
       [9, 2],
       [9, 3],
       [9, 4]])

In [6]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [7]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [8]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [9]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])